apiVersion: v1
kind: Service
metadata:
  name: m2
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: m2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m2
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m2
  template:
    metadata:
      labels:
        app: m2
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-db-creds: 'database/creds/db-app'
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {
          {{- with secret "database/creds/db-app" -}}
          "db_connection": "postgresql://{{ .Data.username }}:{{ .Data.password }}@postgres:5432/wizard"
          {{- end }}
          }
        vault.hashicorp.com/role: 'm2'
    spec:
      containers:
        - image: ezegrosfeld/m2
          name: m2
          ports:
            - containerPort: 8080
          env:
            - name: 'CONFIG_FILE'
              value: '/vault/secrets/db-creds'
      serviceAccountName: m2
