apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: m1
spec:
  protocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: m1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: m1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m1
  template:
    metadata:
      labels:
        app: m1
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: m1
          image: ezegrosfeld/m1
          env:
            - name: M2_URL
              value: 'http://m2'
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: m1
