apiVersion: v1
kind: Service
metadata:
  name: m2
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: m2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m2
  template:
    metadata:
      labels:
        app: m2
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - image: ezegrosfeld/m2
          name: m2
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: m2
